/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 rubikcube.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./rubikcube.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Cube_3.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Cube_4.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Cube001_3.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube002_2.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Cube002_3.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Cube002_4.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube003_2.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Cube003_3.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube004_2.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube005_2.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Cube005_3.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Cube006_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cube006_3.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Cube006_4.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Cube007_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube007_2.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cube007_3.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Cube008_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube008_2.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cube008_3.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Cube008_4.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Cube009_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube009_2.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Cube009_3.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube010_2.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Cube011_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube011_2.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Cube011_3.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Cube012_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube012_2.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Cube014_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube014_2.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Cube015_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube015_2.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cube015_3.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Cube016_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube016_2.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cube017_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube017_2.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cube017_3.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Cube018_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube018_2.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube018_3.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Cube018_4.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Cube019_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube019_2.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube019_3.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Cube020_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube020_2.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube020_3.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Cube020_4.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Cube021_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube021_2.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube021_3.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Cube022_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube022_2.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube023_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube023_2.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube023_3.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Cube024_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube024_2.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube024_3.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cube024_4.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Cube025_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube025_2.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube025_3.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cube026_1.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube026_2.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube026_3.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cube026_4.geometry} material={materials['Material.004']} />
    </group>
  )
}

useGLTF.preload('./rubikcube.gltf')
